version: '3.8'

volumes:
  pg_data: {}

services:
  bot:
    image: "${BOT_IMAGE_NAME:-tg_bot-image}"
    container_name: "${BOT_CONTAINER_NAME:-tg_bot-container}"
    stop_signal: SIGINT
    build:
      context: .
    volumes:
    - .:/usr/src/app/inside_gpt_bot
    command: sh -c "alembic upgrade head && python3 -m bot"
    restart: always
    env_file:
      - ".env"
    depends_on:
      - psql_db
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  psql_db:
    image: postgres:15
    container_name: "${DB_CONTAINER_NAME:-psql-container}"
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
