"""a

Revision ID: 9aebec9db34f
Revises: 2f3ea79ca7e6
Create Date: 2023-08-08 23:43:04.257055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aebec9db34f'
down_revision = '2f3ea79ca7e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('texts', sa.Column('title', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'texts', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'texts', type_='unique')
    op.drop_column('texts', 'title')
    # ### end Alembic commands ###
